NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ShipmentAgency.example.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ShipmentAgency.example.com-cert.pem
    OrganizationalUnitIdentifier: peer
